export const flights = [
  {
    airline: 'Emirates',
    flightNumber: 'EK202',
    departureCity: 'Kabul',
    departureCode: 'KBL',
    departureTime: '22:30',
    departureDate: '2025-04-10',
    arrivalCity: 'Dubai',
    arrivalCode: 'DXB',
    arrivalTime: '01:30',
    arrivalDate: '2025-04-11',
    duration: '4h 00m',
    travelClass: 'First Class',
    price: 1200,
  },
  {
    airline: 'Ariana Afghan Airlines',
    flightNumber: 'AR455',
    departureCity: 'Kabul',
    departureCode: 'KBL',
    departureTime: '06:15',
    departureDate: '2025-04-11',
    arrivalCity: 'Istanbul',
    arrivalCode: 'IST',
    arrivalTime: '10:45',
    arrivalDate: '2025-04-11',
    duration: '5h 30m',
    travelClass: 'Business',
    price: 850,
  },
  {
    airline: 'Kam Air',
    flightNumber: 'KA310',
    departureCity: 'Kabul',
    departureCode: 'KBL',
    departureTime: '09:00',
    departureDate: '2025-04-12',
    arrivalCity: 'Herat',
    arrivalCode: 'HEA',
    arrivalTime: '10:30',
    arrivalDate: '2025-04-12',
    duration: '1h 30m',
    travelClass: 'Economy',
    price: 150,
  },
  {
    airline: 'Pamir Airways',
    flightNumber: 'PA107',
    departureCity: 'Kabul',
    departureCode: 'KBL',
    departureTime: '11:00',
    departureDate: '2025-04-13',
    arrivalCity: 'Kandahar',
    arrivalCode: 'KDH',
    arrivalTime: '12:15',
    arrivalDate: '2025-04-13',
    duration: '1h 15m',
    travelClass: 'Economy',
    price: 130,
  },
  {
    airline: 'Flydubai',
    flightNumber: 'FZ512',
    departureCity: 'Kandahar',
    departureCode: 'KDH',
    departureTime: '14:45',
    departureDate: '2025-04-13',
    arrivalCity: 'Dubai',
    arrivalCode: 'DXB',
    arrivalTime: '17:00',
    arrivalDate: '2025-04-13',
    duration: '3h 15m',
    travelClass: 'Business',
    price: 700,
  },
  {
    airline: 'FlyLagman',
    flightNumber: 'FZ512',
    departureCity: 'Kandahar',
    departureCode: 'KDH',
    departureTime: '14:45',
    departureDate: '2025-04-13',
    arrivalCity: 'Dubai',
    arrivalCode: 'DXB',
    arrivalTime: '17:00',
    arrivalDate: '2025-04-13',
    duration: '3h 15m',
    travelClass: 'Business',
    price: 700,
  },
  {
    airline: 'FlyHerat',
    flightNumber: 'FZ512',
    departureCity: 'Kandahar',
    departureCode: 'KDH',
    departureTime: '14:45',
    departureDate: '2025-04-13',
    arrivalCity: 'Dubai',
    arrivalCode: 'DXB',
    arrivalTime: '17:00',
    arrivalDate: '2025-04-13',
    duration: '3h 15m',
    travelClass: 'Business',
    price: 700,
  },
  {
    airline: 'Flydubai',
    flightNumber: 'FZ512',
    departureCity: 'Kandahar',
    departureCode: 'KDH',
    departureTime: '14:45',
    departureDate: '2025-04-13',
    arrivalCity: 'Dubai',
    arrivalCode: 'DXB',
    arrivalTime: '17:00',
    arrivalDate: '2025-04-13',
    duration: '3h 15m',
    travelClass: 'Business',
    price: 700,
  },
  {
    airline: 'Turkish Airlines',
    flightNumber: 'TK320',
    departureCity: 'Herat',
    departureCode: 'HEA',
    departureTime: '07:30',
    departureDate: '2025-04-14',
    arrivalCity: 'Istanbul',
    arrivalCode: 'IST',
    arrivalTime: '10:00',
    arrivalDate: '2025-04-14',
    duration: '3h 30m',
    travelClass: 'Economy',
    price: 600,
  },
  {
    airline: 'Emirates',
    flightNumber: 'EK405',
    departureCity: 'Herat',
    departureCode: 'HEA',
    departureTime: '20:00',
    departureDate: '2025-04-14',
    arrivalCity: 'Abu Dhabi',
    arrivalCode: 'AUH',
    arrivalTime: '22:00',
    arrivalDate: '2025-04-14',
    duration: '2h 00m',
    travelClass: 'First Class',
    price: 1100,
  },
  {
    airline: 'Kam Air',
    flightNumber: 'KA628',
    departureCity: 'Mazar-i-Sharif',
    departureCode: 'MZR',
    departureTime: '13:45',
    departureDate: '2025-04-15',
    arrivalCity: 'Dubai',
    arrivalCode: 'DXB',
    arrivalTime: '17:15',
    arrivalDate: '2025-04-15',
    duration: '4h 30m',
    travelClass: 'Business',
    price: 900,
  },
  {
    airline: 'Ariana Afghan Airlines',
    flightNumber: 'AR778',
    departureCity: 'Kandahar',
    departureCode: 'KDH',
    departureTime: '05:20',
    departureDate: '2025-04-15',
    arrivalCity: 'Delhi',
    arrivalCode: 'DEL',
    arrivalTime: '08:30',
    arrivalDate: '2025-04-15',
    duration: '3h 10m',
    travelClass: 'Economy',
    price: 500,
  },
  {
    airline: 'Pamir Airways',
    flightNumber: 'PA203',
    departureCity: 'Kabul',
    departureCode: 'KBL',
    departureTime: '08:00',
    departureDate: '2025-04-16',
    arrivalCity: 'Mazar-i-Sharif',
    arrivalCode: 'MZR',
    arrivalTime: '09:15',
    arrivalDate: '2025-04-16',
    duration: '1h 15m',
    travelClass: 'Economy',
    price: 120,
  },
  {
    airline: 'Bilal Afghan Airlines',
    flightNumber: 'BA551',
    departureCity: 'Herat',
    departureCode: 'HEA',
    departureTime: '15:30',
    departureDate: '2025-04-16',
    arrivalCity: 'Kandahar',
    arrivalCode: 'KDH',
    arrivalTime: '17:00',
    arrivalDate: '2025-04-16',
    duration: '1h 30m',
    travelClass: 'Economy',
    price: 140,
  },
  {
    airline: 'Kam Air',
    flightNumber: 'KA990',
    departureCity: 'Kandahar',
    departureCode: 'KDH',
    departureTime: '10:15',
    departureDate: '2025-04-17',
    arrivalCity: 'Doha',
    arrivalCode: 'DOH',
    arrivalTime: '12:45',
    arrivalDate: '2025-04-17',
    duration: '2h 30m',
    travelClass: 'Business',
    price: 780,
  },
  {
    airline: 'Ariana Afghan Airlines',
    flightNumber: 'AR332',
    departureCity: 'Kabul',
    departureCode: 'KBL',
    departureTime: '18:00',
    departureDate: '2025-04-17',
    arrivalCity: 'Doha',
    arrivalCode: 'DOH',
    arrivalTime: '20:30',
    arrivalDate: '2025-04-17',
    duration: '2h 30m',
    travelClass: 'Economy',
    price: 760,
  },
  {
    airline: 'Emirates',
    flightNumber: 'EK517',
    departureCity: 'Mazar-i-Sharif',
    departureCode: 'MZR',
    departureTime: '23:10',
    departureDate: '2025-04-18',
    arrivalCity: 'Dubai',
    arrivalCode: 'DXB',
    arrivalTime: '02:00',
    arrivalDate: '2025-04-19',
    duration: '4h 50m',
    travelClass: 'First Class',
    price: 1250,
  },
  {
    airline: 'Kam Air',
    flightNumber: 'KA470',
    departureCity: 'Herat',
    departureCode: 'HEA',
    departureTime: '06:45',
    departureDate: '2025-04-18',
    arrivalCity: 'Tehran',
    arrivalCode: 'IKA',
    arrivalTime: '08:30',
    arrivalDate: '2025-04-18',
    duration: '1h 45m',
    travelClass: 'Economy',
    price: 350,
  },
  {
    airline: 'Pamir Airways',
    flightNumber: 'PA689',
    departureCity: 'Kabul',
    departureCode: 'KBL',
    departureTime: '12:30',
    departureDate: '2025-04-19',
    arrivalCity: 'Islamabad',
    arrivalCode: 'ISB',
    arrivalTime: '13:45',
    arrivalDate: '2025-04-19',
    duration: '1h 15m',
    travelClass: 'Economy',
    price: 200,
  },
  {
    airline: 'Bilal Afghan Airlines',
    flightNumber: 'BA404',
    departureCity: 'Kandahar',
    departureCode: 'KDH',
    departureTime: '16:00',
    departureDate: '2025-04-19',
    arrivalCity: 'Karachi',
    arrivalCode: 'KHI',
    arrivalTime: '17:30',
    arrivalDate: '2025-04-19',
    duration: '1h 30m',
    travelClass: 'Economy',
    price: 220,
  },
  {
    airline: 'Ariana Afghan Airlines',
    flightNumber: 'AR912',
    departureCity: 'Kabul',
    departureCode: 'KBL',
    departureTime: '07:50',
    departureDate: '2025-04-20',
    arrivalCity: 'Moscow',
    arrivalCode: 'SVO',
    arrivalTime: '12:00',
    arrivalDate: '2025-04-20',
    duration: '4h 10m',
    travelClass: 'Business',
    price: 980,
  },
  {
    airline: 'Kam Air',
    flightNumber: 'KA815',
    departureCity: 'Mazar-i-Sharif',
    departureCode: 'MZR',
    departureTime: '20:20',
    departureDate: '2025-04-20',
    arrivalCity: 'Tashkent',
    arrivalCode: 'TAS',
    arrivalTime: '23:00',
    arrivalDate: '2025-04-20',
    duration: '2h 40m',
    travelClass: 'Economy',
    price: 410,
  },
  {
    airline: 'Flydubai',
    flightNumber: 'FZ330',
    departureCity: 'Herat',
    departureCode: 'HEA',
    departureTime: '13:15',
    departureDate: '2025-04-21',
    arrivalCity: 'Muscat',
    arrivalCode: 'MCT',
    arrivalTime: '15:00',
    arrivalDate: '2025-04-21',
    duration: '1h 45m',
    travelClass: 'Business',
    price: 680,
  },
  {
    airline: 'Pamir Airways',
    flightNumber: 'PA558',
    departureCity: 'Kabul',
    departureCode: 'KBL',
    departureTime: '17:10',
    departureDate: '2025-04-21',
    arrivalCity: 'Baku',
    arrivalCode: 'GYD',
    arrivalTime: '21:00',
    arrivalDate: '2025-04-21',
    duration: '3h 50m',
    travelClass: 'Economy',
    price: 540,
  },
  {
    airline: 'Ariana Afghan Airlines',
    flightNumber: 'AR678',
    departureCity: 'Kandahar',
    departureCode: 'KDH',
    departureTime: '19:45',
    departureDate: '2025-04-21',
    arrivalCity: 'Dubai',
    arrivalCode: 'DXB',
    arrivalTime: '22:15',
    arrivalDate: '2025-04-21',
    duration: '2h 30m',
    travelClass: 'Business',
    price: 800,
  },
];
